# Generated by Django 5.2.8 on 2026-02-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useractivatetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivateToken',
        ),
    ]
