# Generated by Django 5.2.8 on 2026-02-14 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'drink_types',
            },
        ),
        migrations.CreateModel(
            name='DrinkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_date', models.DateField(verbose_name='記録日')),
                ('drink_name', models.CharField(max_length=100, verbose_name='飲み物名')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='店舗名')),
                ('maker_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='メーカー名')),
                ('taste_rating', models.IntegerField(choices=[(0, '好き'), (1, '普通'), (2, '苦手')])),
                ('total_rating', models.IntegerField(verbose_name='総合評価')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='drink_records/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drink_records',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('drink_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='drink_app.drinktype')),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='DrinkRecordIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drink_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink_app.drinkrecord')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drink_app.ingredient')),
            ],
            options={
                'db_table': 'drink_record_ingredients',
            },
        ),
        migrations.AddField(
            model_name='drinkrecord',
            name='ingredients',
            field=models.ManyToManyField(related_name='drink_records', through='drink_app.DrinkRecordIngredient', to='drink_app.ingredient'),
        ),
        migrations.AddConstraint(
            model_name='drinkrecordingredient',
            constraint=models.UniqueConstraint(fields=('drink_record', 'ingredient'), name='uniq_record_ingredient'),
        ),
    ]
