# Generated by Django 5.2.8 on 2026-02-15 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkrecord',
            name='drink_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='drink_records', to='drink_app.drinktype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drinkrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drink_records/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='drinkrecord',
            name='taste_rating',
            field=models.IntegerField(choices=[(0, '好き'), (1, '普通'), (2, '苦手')], verbose_name='味の評価'),
        ),
        migrations.AlterField(
            model_name='drinktype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='飲み物の種類'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='素材'),
        ),
    ]
