# Generated by Django 5.2.8 on 2026-02-17 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink_app', '0002_drinkrecord_drink_type_alter_drinkrecord_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasteFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'taste_features',
            },
        ),
        migrations.AlterField(
            model_name='drinkrecord',
            name='drink_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drink_records', to='drink_app.drinktype', verbose_name='飲み物の種類'),
        ),
        migrations.AlterField(
            model_name='drinkrecord',
            name='ingredients',
            field=models.ManyToManyField(related_name='drink_records', through='drink_app.DrinkRecordIngredient', to='drink_app.ingredient', verbose_name='素材'),
        ),
        migrations.AlterField(
            model_name='drinkrecord',
            name='total_rating',
            field=models.IntegerField(choices=[(0, '☆☆☆'), (1, '★☆☆'), (2, '★★☆'), (3, '★★★')], verbose_name='総合評価'),
        ),
        migrations.AlterField(
            model_name='drinktype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='DrinkRecordTasteFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drink_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink_app.drinkrecord')),
                ('taste_feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drink_app.tastefeature')),
            ],
            options={
                'db_table': 'drink_record_taste_features',
            },
        ),
        migrations.AddField(
            model_name='drinkrecord',
            name='taste_features',
            field=models.ManyToManyField(related_name='drink_records', through='drink_app.DrinkRecordTasteFeature', to='drink_app.tastefeature', verbose_name='味の特徴'),
        ),
        migrations.AddConstraint(
            model_name='drinkrecordtastefeature',
            constraint=models.UniqueConstraint(fields=('drink_record', 'taste_feature'), name='uniq_record_taste_feature'),
        ),
    ]
