# Generated by Django 5.2.8 on 2026-02-22 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink_app', '0003_tastefeature_alter_drinkrecord_drink_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkrecord',
            name='drink_name',
            field=models.CharField(max_length=100, verbose_name='*飲み物名'),
        ),
        migrations.AlterField(
            model_name='drinkrecord',
            name='drink_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drink_records', to='drink_app.drinktype', verbose_name='*飲み物の種類'),
        ),
        migrations.AlterField(
            model_name='drinkrecord',
            name='ingredients',
            field=models.ManyToManyField(related_name='drink_records', through='drink_app.DrinkRecordIngredient', to='drink_app.ingredient', verbose_name='*素材'),
        ),
        migrations.AlterField(
            model_name='drinkrecord',
            name='recorded_date',
            field=models.DateField(verbose_name='*記録日'),
        ),
        migrations.AlterField(
            model_name='drinkrecord',
            name='taste_features',
            field=models.ManyToManyField(related_name='drink_records', through='drink_app.DrinkRecordTasteFeature', to='drink_app.tastefeature', verbose_name='*味の特徴'),
        ),
        migrations.AlterField(
            model_name='drinkrecord',
            name='taste_rating',
            field=models.IntegerField(choices=[(0, '♡好き'), (1, '⚪︎普通'), (2, '×苦手')], verbose_name='*味の評価'),
        ),
        migrations.AlterField(
            model_name='drinkrecord',
            name='total_rating',
            field=models.IntegerField(choices=[(0, '☆☆☆'), (1, '★☆☆'), (2, '★★☆'), (3, '★★★')], verbose_name='*総合評価'),
        ),
    ]
